### ISSUE TITLE
Support for jsxhint

### ISSUE THREAD

**Issue by Andersos** [finn-no/js-code-style#2]
In [Unleash](https://github.com/finn-no/unleash) we use [React](http://facebook.github.io/react/) so we need to run [jsxhint](https://github.com/STRML/JSXHint). Any thoughts of how this should be handled? (https://github.com/finn-no/unleash/issues/62)

**Comment by ivarconr** [comment]
Could js-code-style have an option for running with [jsxhint](https://www.npmjs.com/package/jsxhint) insted of jshint?

**Comment by Andersos** [comment]
I think last time I looked at this js-code-style was using extends and I think jsxhint dose not support that yet.

**Comment by phillipj** [comment]
Any updates on this? Are you linting JSX in your project yet @ivarconr ?

**Comment by ivarconr** [comment]
We have manually copied the rules and uses [JSXHint](https://github.com/STRML/JSXHint) for now. Not the best solutions, but have not had time to see whats needed to make this work with js-code-style.

**Comment by Andersos** [comment]
Looks like we should consider a new [direction](https://medium.com/@STRML/ending-jsxhint-1c09ed36cca9) instead of getting JSHint to support JSX and ES6.

**Comment by phillipj** [comment]
Pretty sure @gregersrygg had some eslint migration plans?

**Comment by gregersrygg** [comment]
Yes, I would like to investigate switching to eslint. It's much more flexible, and they have (or are working on) JSX-support. But haven't had time to check it out yet :(

The thought when creating js-code-style is that it can run multiple tools. Is it possible to run jsxhint only with the jsx-rules? I'm a bit sceptical that they wrap jshint...

**Comment by Andersos** [comment]
Looks like we are going away from jshint.
