### ISSUE TITLE
CamelCase check

### ISSUE THREAD

**Issue by Andersos** [finn-no/js-code-style#4]
It feels redundant that both jscs and jshint checks for this:

[jshint](http://jshint.com/docs/options/#camelcase)
`"camelcase"     : true`

jscs:
`"requireCamelCaseOrUpperCaseIdentifiers": true`

I had to ignore the camel case rule for one line in Unleash and then I had to find a way to ignore both of the rulesets.

**Comment by gregersrygg** [comment]
jscs was added just as a test. It's not official. I'm attempted to delete it, but that would be a breaking change.
