### ISSUE TITLE
Replace jshint and custom rules in favor of eslint-config-spt

### ISSUE THREAD

**Issue by gregersrygg** [finn-no/js-code-style#7]
https://github.com/schibsted/eslint-config-spt

**Comment by phillipj** [comment]
Most of the work has already been done on the `eslinitify` branch. Waiting for eslint-config-spt to become public before opening a PR.

**Comment by gregersrygg** [comment]
@phillipj Sweet! To me it looks like it is public :) https://www.npmjs.com/package/eslint-config-spt

**Comment by phillipj** [comment]
:dancers:
